### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#113]
## Features
- [ ] #44 Add reduction attribute
- [ ] #57 Add support to use __constant in GPU modes
- [ ] #66 ARM Support
- [ ] #87 Use compiler-defined macros in the preprocessor
- [ ] #96  Consolidate primitive types
- [ ] #101 Use proper locks when compiling kernels
- [ ] #115 Include standard math functions in OKL
- [ ] #116 Allow outer and inner loop annotating for CUDA/OpenCL
- [ ] #117 `@barrier` for GPU modes
- [ ] #118 Add `@atomic` for atomic operations
- [ ] #123 Delegate nested-kernel launching to the backends
- [ ] #124 Separate public and private API

### Custom Attributes

To promote the custom kernel argument types, we are adding the ability to create custom OKL attributes. Custom attributes can be used to mirror the custom kernel argument type modifications in the kernel code.

To see an example of this use, check `occa::array`.

An additional and more general use of custom attributes is the runtime modification of the kernel AST. We will provide a toolchain for modifying the kernel AST that hopes to facilitate adding custom backends.

### Reduction

Unfortunately, the OKL programming model doesn't easily allow for reductions. Due to a large need in reduction kernels, we want to formalize the way backends handle redutions. The goal is to make it easier on users and maintain high performance.

Concept:
```c++
@reduction void dot_norm(const int entries,
                         const float *a,
                         const float *b,
                         @reduce float dot,
                         @reduce float a_norm2,
                         @reduce float b_norm2) {

  for (int i = 0; i < entries; ++i; reduce(32)) {
    dot += a[i] * b[i];
    a_norm2 += a[i] * a[i];
    b_norm2 += b[i] * b[i];
  }
}
```

## Languages

We will officially support the following frontends in the 1.1 release

| Language | Github Repository                               |
| -------- | ----------------------------------------------- |
| C        | [libocca/occa](https://github.com/libocca/occa) |
| C++      | [libocca/occa](https://github.com/libocca/occa) |
| Python   | [libocca/occa-python](https://github.com/libocca/occa-python) |
| Python   | [libocca/occa-fortran](https://github.com/libocca/occa-fortran) |
