### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by dmed256** [libocca/occa#47]
## Version 1.0

We're aiming for a production-grade release with 1.0. A large amount of refactoring is being done for the API and OKL parser.

Issues
- [x] #51: Add basic linear algebra routines to `occa::array`
- [x] #49: Add custom attributes
- [x] #52: Update C bindings
- [ ] #46: Create 1.0 documentation
- [x] #48: Add coverage metrics

### [libocca.org](https://libocca.org)

We're releasing documentation with
- Getting started
- OCCA programming model
- OKL programming model
- API documentation
- Extending OCCA

## Testing and Coverage

This has been a long and crucial part missing in our release process. We are going to be making testing a required part in our release process. Coverage metrics will also be included.

### Developer Tools

Helper methods were added to facilitate collaboration and extending OCCA in other codebases.

Examples include:
- System calls
- Environment variables
- Finding files with/without custom URI prefixes (e.g. `occa://occa/foo.okl`)
- Hashing files and objects
- Caching files such as compiled binaries
- Locating cached binaries
- String manipulation

### Properties

We're aiming to unify backends through a general API. However, we would also like to expose various features unique to different backends.

For example:
- Memory allocation types
  - CUDA and OpenCL have texture memory
  - Possible memory locations in future architectures
- Device features
  - Expose features backend devices require. A list of cores Threads mode is pinning to, `deviceID` in OpenCL and CUDA, etc
- Kernels
  - Defines and headers
  - Possible extensions to kernel building

We added properties in 1.0 to help create a more flexible API. Properties use the standard JSON representation to maintain a 1-1 mapping from data to string.

The following JS augmentations are also supported:
- Object keys do not need to be stringified
- Single quotes can also be used for strings
- Trailing commas can be used

```js
{ mode: 'Serial', }
```

While we support loading JSON strings with `occa::json`, properties are always JSON objects. Hence, we also support ignoring braces when initializing properties from a string.

```c++
occa::properties(mode: 'Serial')
```

### Modes

OCCA modes are composed of 3 classes: device, kernel, and memory. Modes can now be added outside of OCCA through registering the modes. The mode constructor will register the classes with its respective mode.

```c++
occa::mode<openmp::modeInfo,
           openmp::device,
           openmp::kernel,
           openmp::memory> mode("OpenMP");
```

## OKL Parser

The OKL kernel language is one of the key features in OCCA. Adding JIT compilation of kernels gives us the flexibility of reusing kernels for different OCCA modes. We are refactoring the parser from the bottom up for robustness and flexibility.

### Custom Kernel Arguments

Custom C++ classes can now be passed as kernel arguments by adding the `occa::kernelArg` cast operator

```c++
operator occa::kernelArg ();
```

The class is not restricted by OCCA in the amount of arguments or types it can add to the kernel call. The backend could restrict the number of arguments or types, for example 256 is the maximum arguments in CPU modes.

To see an example of this use, check `occa::array`.

*Note:* The OKL kernel has to match the same number arguments and types.

## Linear Algebra

We're adding some common vector operations and linear algebra routines to `occa::array`
- `+ - * /` operations
- Norms (L1, L2, Lp, Linf)
- max, min
- dot

## Languages

We will officially support the following frontends in the 1.0 release

| Language | Github Repository                               |
| -------- | ----------------------------------------------- |
| C        | [libocca/occa](https://github.com/libocca/occa) |
| C++      | [libocca/occa](https://github.com/libocca/occa) |
| Python   | libocca/occa-python                             |

We'll be adding the following in the 1.1 release

| Language | Github Repository    |
| -------- | -------------------- |
| Python  | libocca/occa-python |
| Fortran  | libocca/occa-fortran |

Potential future languages

| Language | Github Repository    |
| -------- | -------------------- |
| Java     | libocca/occa-java    |
| Julia    | libocca/occa-julia   |

Documentation and testing will be included
