### ISSUE TITLE
Getting Started (New User) Guide

### ISSUE THREAD

**Issue by kris-rowe** [libocca/occa#557]
Concise instructions for getting started should be provided in the [README](https://github.com/libocca/occa/tree/community-profile); however, there are likely topics which require more explanation without becoming overly technical.

## Todo

- [ ] Review existing documentation for new users (e.g. see docs/user-guide)
- [ ] Review the updated [README](https://github.com/libocca/occa/tree/community-profile)
- [ ] Identify incomplete or unclear information from a new user perspective
- [ ] Update README and docs/user-guide files as appropriate
- [ ] Remove unnecessary files from docs/user-guide
