### ISSUE TITLE
Runtime API Documentation

### ISSUE THREAD

**Issue by kris-rowe** [libocca/occa#559]
Documentation for many of the runtime classes is available via the [libocca.org](https://libocca.org/#/api/) website, however there are gaps in several areas.

Currently this is auto generated from source code comments using Doxygen.

## Todo

- [ ] Review existing runtime API documentation at [libocca.org](https://libocca.org/#/api/)
- [ ] Identify classes or concepts which are have incomplete or missing documentation (e.g. Streams, Background Device etc.)
- [ ] Add documentation via source code and separate files as appropriate
- [ ] Determine the optimal means of incorporating auto-generated (Doxygen) files into the OCCA GitHub wiki
