### ISSUE TITLE
OKL Documentation

### ISSUE THREAD

**Issue by kris-rowe** [libocca/occa#560]
Many of the OKL attributes are documented on the [libocca.org](https://libocca.org/#/guide/okl/introduction) website; however, some newer attributes are missing.

## Todo

- [ ] Review existing documentation at [libocca.org](https://libocca.org/#/guide/okl/introduction) 
- [ ] Identify attributes which have incomplete or missing documentation&mdash;e.g., `@tile`,`@barrier`, `@atomic`, `@max_inner_dims`
- [ ] Update documentation in docs/guide/okl
