### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by kris-rowe** [libocca/occa#562]
It would be helpful for users to have a more progressive set of examples, grouped into subdirectories by simple to more advanced usage.

> Currently OCCA's automated testing uses the existing examples. Updating the examples will break the automated testing. This should be dealt with in a separate issue.

## Todo

- [ ] Review existing examples
- [ ] Outline a set of progressive examples demonstrating simple, intermediate, and advanced OCCA use cases
- [ ] Refactor examples directory
- [ ] Implement and test new examples
